# Generated by Django 3.0.7 on 2020-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201009_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/static/blog/images/default.png', null=True, upload_to='images/'),
        ),
    ]
