# Generated by Django 3.0.7 on 2021-05-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='posts',
        ),
    ]
