# Generated by Django 3.0.7 on 2021-05-08 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210508_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
